### ISSUE TITLE
Add Validations

### ISSUE THREAD

**Issue by jvillane** [spring-guides/gs-producing-web-service#10]
Maybe it'll be very useful (it took me a couple of hours to find the way) to document the way of validate the request using only configurations...

`@Override
public void addInterceptors(List<EndpointInterceptor> interceptors) {
    PayloadValidatingInterceptor validatingInterceptor = new PayloadValidatingInterceptor();
    validatingInterceptor.setValidateRequest(true);
    validatingInterceptor.setValidateResponse(true);
    validatingInterceptor.setXsdSchema(countriesSchema());
    interceptors.add(validatingInterceptor);
}`

Thanks for your guides! They rock

**Comment by gregturn** [comment]
Whereas I like you expanding this guide to demonstrate validation @jvillane, I believe this would take the guide beyond the simple thing it is - demonstration of SOAP using Spring. Perhaps this would be good material for you to write a blog article about?
