### ISSUE TITLE
Error:(9, 49) java: package io.spring.guides.gs_producing_web_service does not exist

### ISSUE THREAD

**Issue by aminabvaal** [spring-guides/gs-producing-web-service#15]
what is that..... why you ignore io in .gitignore file
 https://github.com/spring-guides/gs-producing-web-service/blob/master/complete/src/main/java/.gitignore

**Comment by dsyer** [comment]
The "io" package is auto-generated. Please run the build from the command line.

**Comment by TEMIMO** [comment]
Had the same problem. Right click on pom.xm -> maven -> Generate Sources and Update Folders. And check that pom hasn't red underlines.
