### ISSUE TITLE
Support for jdk 11

### ISSUE THREAD

**Issue by patanjalic** [spring-guides/gs-producing-web-service#16]
I was trying this exercise on jdk11 with no luck yet. Dealing with jaxb xml xsd soap is a complete mess now with 11. 
Can you please us by updating this example with latest jdk

**Comment by gregturn** [comment]
Since Spring is based on JDK 8, we aren’t quite ready to bump up all the guides to JDK 11. 

But to assist you with Spring WS and JDK 11, please check out the project’s Pom.cml file. You’ll discover a profile used to add the proper dependencies that have seen been removed from JDK 11.

**Comment by sullyslegacy** [comment]
Now that we have Spring Boot 2.1.3.RELEASE are there any plans for JDK 11 now?
