### ISSUE TITLE
jaxb2-maven-plugin generates sources in incorrect location

### ISSUE THREAD

**Issue by StevenGeens** [spring-guides/gs-producing-web-service#24]
The jaxb2-maven-plugin is configured to output the generated sources and not clear the output directory:
```
<outputDirectory>${project.basedir}/src/main/java</outputDirectory>
<clearOutputDir>false</clearOutputDir>
```
This is not desirable for 2 reasons:
* It's generally considered best to store generated code together with the normal project code. (See [this](https://stackoverflow.com/questions/7766338/maven-how-to-handle-generated-classes) stackoverflow question for a discussion.)
* Because the code generation shouldn't delete the normal sources, the `clearOutputDir` option is set to `false`. This has the unhappy side effect that certain changes to the XSD would not be correctly represented in the generated code. (e.g.: Deletion of an XML element in the XSD would not remove the generated java class.)

**Comment by StevenGeens** [comment]
I've created pull request #23 for this.

**Comment by gregturn** [comment]
Thanks @StevenGeens .
