### ISSUE TITLE
Describe that an  explicit XSD file location is required in maven to generate source files

### ISSUE THREAD

**Issue by NimaVibeVans** [spring-guides/gs-producing-web-service#28]
Excellent Guide. I just had one issue using Java 13 & maven 3.6.2. When editing the pom.xml I had to specify countries.xsd otherwise I was not able to generate the source files. 
CURRENT DOC

```
<configuration>
		<sources>
			<source>${project.basedir}/src/main/resources/</source>
		</sources>
	</configuration>
```

ABLE TO GENERATE SOURCE BY SPECIFYING THE XSD FILE

```
<configuration>
		<sources>
			<source>${project.basedir}/src/main/resources/countries.xsd</source>
		</sources>
	</configuration>
```

**Comment by dsyer** [comment]
Works for me. Can you reproduce your error? Can you show some steps to reproduce?

**Comment by arturwp** [comment]
Where is an empty application.properties file - you can't generate sources for this.
I'm talking about project generated by Spring Initializr.

**Comment by dsyer** [comment]
@arturwp The guide explicitly says "create an XSD file..." and goes on to give the location and the contents. You can't be much more explicit than that. Maybe I misunderstood (your comment doesn't seem relevant to the OP)?

**Comment by arturwp** [comment]
There is nothing wrong with XSD file, but with pom.xml:

<configuration>
		<sources>
			<source>${project.basedir}/src/main/resources/</source>
		</sources>
</configuration>

In this configuration compiler tries to generate source files for all files in "resources" directory, including empty application.properties.

**Comment by dsyer** [comment]
Ah, I see. And that file isn't present in the "complete" sample. That makes some sense finally.
