### ISSUE TITLE
How to perform security?

### ISSUE THREAD

**Issue by GlennVanSchil** [spring-guides/gs-producing-web-service#3]
Do you have any guides on how to implement ws-security on a soap server like this one? 
We are looking for a encryption of our SOAP content and a authentication on the SOAP.

**Comment by poutsma** [comment]
Not a guide, but there is a sample here: https://github.com/spring-projects/spring-ws-samples/tree/master/airline

**Comment by GlennVanSchil** [comment]
Thank you for this example, I will look into this!

**Comment by GlennVanSchil** [comment]
On first hand it does look like something I need for my project, but I'm still pretty new to spring and soap and this is a pretty big and advanced project with a lot of files and folders and it's hard to find my way around in it. I need something more basic to get started.

**Comment by gregturn** [comment]
Another example that is perhaps smaller is found at https://github.com/gregturn/learning-spring-ws. This is what I used to tinker around with Spring WS. It has both a server and a client, and they communicate with a very simple message. There are data files included.

In addition, there is a security branch with security switched on between the two.
