### ISSUE TITLE
Question : Why can my build not find jaxb2-maven-plugin version 2.5.0?

### ISSUE THREAD

**Issue by jacquesvdm7** [spring-guides/gs-producing-web-service#31]
When Adding the jaxb2-maven-plugin plugin to my code the version 2.5.0 does not exist and I have to change it to 1.6 which then renders the sources XML tag invalid (error "element is not allowed here").

 I must admit I did not compile your code I just added the plugin required for the XSD and off cause the other dependencies for the SOAP web service.
My spring release is 2.2.4.RELEASE
JVM 1.8

**Comment by dsyer** [comment]
Are you using Maven? The plugin is in Maven Central. Maybe your network environment blocks access to Maven Central? Are you behind a proxy?

**Comment by jacquesvdm7** [comment]
Yes, I am using Maven 3.6 and yes I am behind a corporate proxy but I have my  proxies configured and usually do not have issue pulling dependencies from Maven Central but let me check our local Repo to see what version is present there.

**Comment by jacquesvdm7** [comment]
I checked our Nexus repo and the plugin does exist as per the image attached
![image](https://user-images.githubusercontent.com/69040644/100321672-b830bb00-2fcb-11eb-84f4-44a1ef76ebba.png)

**Comment by dsyer** [comment]
Maybe you had a bad download then? Try deleting your local cache for the plugin and start again?

**Comment by jacquesvdm7** [comment]
Thankyou sir, that did the trick
