### ISSUE TITLE
It seems like on windows "${project.basedir}" does not find the files

### ISSUE THREAD

**Issue by jacquesvdm7** [spring-guides/gs-producing-web-service#32]
**On windows this result in (I replaced the counties.xsd with response.xsd)
${project.basedir}/src/main/resources/templates/response.xsd**
[INFO] Scanning for projects...
[INFO] 
[INFO] -----------------------< africa.absa:training1 >------------------------
[INFO] Building training1 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- jaxb2-maven-plugin:2.5.0:schemagen (default-cli) @ training1 ---
[WARNING] 
+=================== [Incorrect Plugin Configuration Detected]
|
| Property : sources
| Problem  : At least one Java Source file has to be included.
|
+=================== [End Incorrect Plugin Configuration Detected]

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.257 s
[INFO] Finished at: 2020-11-26T10:32:02+02:00
[INFO] ------------------------------------------------------------------------

**When changing the the source to us baseUri rather  (this worked for when using the WSDL generator)
${project.baseUri}/src/main/resources/templates/response.xsd**
[INFO] Scanning for projects...
[INFO] 
[INFO] -----------------------< africa.absa:training1 >------------------------
[INFO] Building training1 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- jaxb2-maven-plugin:2.5.0:schemagen (default-cli) @ training1 ---
[INFO] Ignored given or default sources **[file:///C:/Users/abjmalu/git/springboot/training1//src/main/resources/templates/response.xsd], since it is not an existent file or** directory.
[WARNING] 
+=================== [Incorrect Plugin Configuration Detected]
|
| Property : sources
| Problem  : At least one Java Source file has to be included.
|
+=================== [End Incorrect Plugin Configuration Detected]

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.508 s
[INFO] Finished at: 2020-11-26T10:34:23+02:00
[INFO] ------------------------------------------------------------------------

The file definitely does exist and the URL generated resolves to the file so I don't know why the plugin cant find the file

Your help will be appreciated.

thanks

Jacques

**Comment by dsyer** [comment]
The guide works for me as is (as in the "complete" sample) from WSL. It does not work with `${project.baseUri}` (same error). Can you check that works for you?

**Comment by jacquesvdm7** [comment]
I was running maven goal "jaxb2.schemagen" but it seems I have to run maven goal "jaxb2.xjc". If I run this goal then "${project.basedir}" works fine. I guess its matter of reading the documentation properly.

**Comment by jacquesvdm7** [comment]
Just as closing note , if I run Maven build goal "package" then it build everything without an issue.
