### ISSUE TITLE
Upgrade Spring Boot to the latest version

### ISSUE THREAD

**Issue by Buzzardo** [spring-guides/gs-producing-web-service#45]
Update the guide to use the most recent Spring Boot version.

To do so, change the Spring Boot version in:

initial/build.gradle
initial/pom.xml
complete/build.gradle
complete/pom.xml

**Comment by luiscarbuccia** [comment]
I can help with this

**Comment by igoradulian** [comment]
I can help if it hasn't fixed yet

**Comment by igoradulian** [comment]
Already done. Here is PR:

https://github.com/spring-guides/gs-producing-web-service/pull/46

**Comment by robertmcnees** [comment]
Dependabot is being used in this repository going forward. Closing this issue.
