### ISSUE TITLE
The method setApplicationContext(ApplicationContext) is undefined for the type MessageDispatcherServlet

### ISSUE THREAD

**Issue by tusharbanne** [spring-guides/gs-producing-web-service#7]
```
public ServletRegistrationBean messageDispatcherServlet(ApplicationContext applicationContext) {
		MessageDispatcherServlet servlet = new MessageDispatcherServlet();
		servlet.setApplicationContext(applicationContext);
		servlet.setTransformWsdlLocations(true);
		return new ServletRegistrationBean(servlet, "/ws/*");
	}
```
In the above method,
`servlet.setApplicationContext(applicationContext);`

gives an error

> The method setApplicationContext(ApplicationContext) is undefined for the type MessageDispatcherServlet

when checked the API of MessageDispatcherServlet, there isn't any method setApplicationContext.

Please Help.

**Comment by dsyer** [comment]
`MessageDispatcherServlet` does have that method (it extends `FrameworkServlet`). Maybe you have a copy-paste error?

**Comment by tusharbanne** [comment]
this is the file that is present in my API.

**Comment by tusharbanne** [comment]
[MessageDispatcherServlet.txt](https://github.com/spring-guides/gs-producing-web-service/files/649218/MessageDispatcherServlet.txt)
This is the file that I am referring to.

**Comment by dsyer** [comment]
Yes, well that's a txt file, so I have not way of knowing where it came from. But you see that "FrameworkServlet?" That's the one with the missing method. You might have a classpath issue if it can't be resolved. This project works for me on command line and in IDE.

**Comment by tusharbanne** [comment]
I used the eclipse plugin (Eclipse Class Decompiler plugin) to check the source code and then uploaded the file as text file as git is not allowing me to upload the java file.
I will try to resolve the classpath issue if any.

The project works for me as well. But when I try to write my own ws, it gives this issue.

Also one more thing I would like to ask here is, what will be the endpoint url to load the wsdl.

Thanks.

**Comment by gregturn** [comment]
As of Spring 4, FrameworkServlet implements ApplicationContextAware. So in your own project you must be somehow either NOT be using Spring Boot (which requires Spring 4+), or you are somehow pinning Spring to an old version.

**Comment by tusharbanne** [comment]
@gregturn thanks for pointing that out. It has resolved the issue.
