### ISSUE TITLE
Outdated Gradle JAXB related information

### ISSUE THREAD

**Issue by informatik01** [spring-guides/gs-producing-web-service#9]
Hi.

While reading the official "_[Getting Started Guide: Producing a SOAP web service](https://spring.io/guides/gs/producing-web-service/)_" I have noticed that it says (quote)

> "As gradle does not have a JAXB plugin (yet), it involves an ant task, which makes it a bit more complex than in maven."

Actually that is not true. There are several Gradle JAXB [plugins](https://plugins.gradle.org/search?term=jaxb) available so the ["_Generate domain classes based on an XML schema_"](https://spring.io/guides/gs/producing-web-service/#_generate_domain_classes_based_on_an_xml_schema) section that covers Gradle related configuration can be much simpler if one the available plugins was used instead of writing JAXB task from ground up.

Anyway the "Getting Started Guide" could  at least refer to the list of available Gradle JAXB plugins or mention the fact of their existence.

**Comment by dsyer** [comment]
Excellent! Will you be sending a pull request?

**Comment by informatik01** [comment]
Hm, I knew it, that if I mention that issue with the "Getting Started Guide" I will be asked to provide a ready-made solution solution ))

I just saw the usage of this Gradle [JAXB plugin](https://github.com/rackerlabs/gradle-jaxb-plugin) in one of our projects in the company I work and that you guys mention the lack of the Gradle JAXB plugins. I don't have the **equivalent** config for the specific example right know (writing this from work at the moment), but if nobody is willing to prepare or mention the existence of the relevant Gradle config, I might eventually have a closer look at the example from the "Getting Started Guide", prepare and test the related Gradle configuration and make a pull request. Just don't know when I do this.

_Just as a side note:_ in no way I was trying to make a complaint or offend the developers/creators of the "Getting Started Guide". It was just a suggestion.

**Comment by dsyer** [comment]
No offence taken, I assure you. We are always grateful for any feedback. Pull requests are even nicer though, especially when it's something obscure (gradle and JAXB is in that category IMO).

**Comment by dsyer** [comment]
Closed with #34
